### ISSUE TITLE
PHP 8.2 deprecation notice

### ISSUE THREAD

**Issue by S3b0** [sebkln/content_slug#19]
```
$GLOBALS['TYPO3_CONF_VARS']['SYS']['exceptionalErrors'] = E_WARNING | E_RECOVERABLE_ERROR | E_DEPRECATED | E_USER_DEPRECATED
```

running with TYPO3 11.5.25, PHP 8.2.0 ends up in error

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1476107295: PHP Runtime Deprecation Notice: Creation of dynamic property Sebkln\ContentSlug\Hooks\ReplaceFragment::$typoScriptSetup is deprecated in /.../public/typo3conf/ext/content_slug/Classes/Hooks/ReplaceFragment.php line 36 | TYPO3\CMS\Core\Error\Exception thrown in file /.../public/typo3/sysext/core/Classes/Error/ErrorHandler.php in line 137.

Defining `protected array $typoScriptSetup = [];` property in \Sebkln\ContentSlug\Hooks\ReplaceFragment did fix that issue temporarily on local instance. Even though idk if that's the best solution, I was wondering if that property is even required as I found no further usage in the hook.

**Comment by sebkln** [comment]
Hi Sebastian, thanks for reporting. This was recently fixed with #18, but I only now got the time to draft a new release.
Can you check v3.0.2?
