### ISSUE TITLE
Introduce config option to use header field as source for id / anchor name

### ISSUE THREAD

**Issue by moe2k** [sebkln/content_slug#4]
Thank you for this superb extension!

One suggestion: Typically, in section menus (table of contents, etc.) you only want to anchor-link to elements which have a name, which is usually the one in the `header` field. In this common case, we could save editors a lot of  effort if the extension would simply use this `header` field -by default or configurable- to generate the speaking anchor. This way, the editor only has to fill the custom fragment field if there is no header or if he wants to override it. As a fallback (if neither of both is given) the original CIDs could be used.

**Comment by sebkln** [comment]
Hey Moritz, thanks for your request and kind words!

I understand your usecase, but have to defer this for now. I hope you'll understand.

Currently I'm working on a button that generates a fragment from the current header (#2). This will already simplify work for editors.
Will need some time to understand working with Ajax in the TYPO3 backend, though.

I might consider to add your requested config at a later time.

**Comment by moe2k** [comment]
Awesome!! :-)

**Comment by sebkln** [comment]
Took a while. Glad it still helps. 😄
